---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - el7
      - el8
      - el9
      - debian-10
      - debian-11
      - ubuntu-2004
      - ubuntu-2204
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
